### ISSUE TITLE
bfloat16 Support

### ISSUE THREAD

**Issue by tarlanahad** [jatinchowdhury18/RTNeural#136]
Anyway to use the model with bfloat16 data type?

**Comment by jatinchowdhury18** [comment]
Most RTNeural layers are agnostic to the input data type. Although they're mostly designed to work with floating-point data types, it's also 100% possible to use most RTNeural layers with types like `int` or `std::complex<T>` (although an `RTNeural::TanhActivationT<int>` might not be all that useful).

I haven't tried using RTNeural yet with a `bfloat16` data type, but I imagine it should work, provided that the backend being used with RTNeural also supports `bfloat16`. I don't believe XSIMD has `bfloat16` support. Eigen supports `bfloat16` [as of version 3.4](https://eigen.tuxfamily.org/index.php?title=3.4#New_Major_Features_in_Core), so that should work in RTNeural (RTNeural uses Eigen version 3.4.90). If you're using the STL backend, [C++23](https://en.cppreference.com/w/cpp/types/floating-point) is supposed to have support for `bfloat16`, but I'm not sure what compilers support that feature at the moment.

We should probably add some tests to the RTNeural test suite, to explicitly make sure that `bfloat16` is working with the available layers, and see if there are any potential issues there. I should have some time to work on that next week. In the meantime, if you already have a use-case for `bfloat16`, I'd be curious to hear if you run into issues (or if it "just works")!

**Comment by tarlanahad** [comment]
Tried it doesn't seem to work with std:: bfloat16_t. It needs some of the parts to be statically casted, which solved only some parts of the issue. That would be really nice if you could have a quick look at it. 

So the answer is, it doesn't work.

**Comment by jatinchowdhury18** [comment]
Thanks for the update!

Would it be possible to share a compiler log with any errors messages that may have resulted.

It would also be nice to know the compiler and RTNeural backend that you were using in your test.

If you already have a public repo or something similar where you've been doing your testing, that would be very useful as well!

**Comment by jatinchowdhury18** [comment]
Okay, I finally got around to testing this properly. At the moment, the only compiler I'm aware of that supports `std::float16_t` and `std::bfloat16_t` is GCC-13. With that specific compiler, I was able to add a few tests to RTNeural's test suite to test for compatibility with those floating-point types. The bottom line is that the tests work, however, there are a few disclaimers:

- Support for `float16_t` and `bfloat16_t` only works with the Eigen and STL backends. I don't believe that XSIMD support half-precision floating point types, but I would imagine they might in the future.
- In order for the tests to pass, I had to make make the bounds for acceptable error a bit larger. I think this is to be expected with lower-precision floating point types, but I haven't rigorously confirmed that the accuracy is as good a it can be... there might be some things that we can do in RTNeural to make the accuracy a bit better.
- The tests that I've set up cover a good range of RTNeural's supported layers, but not all of them. If you run into problems using one or two specific layers with half-precision floating point types, then we can investigate those a bit more closely.
- I haven't yet looked at the RTNeural's performance when using these half-precision floating point types. I wouldn't be surprised if it's not very good, depending on the backend/target platform, but that's something we can continue to investigate.
- As mentioned above, using `float16_t`/`bfloat16_t` requires C++23 and GCC-13. As other compilers add support we can enable tests on those platforms as well.
