### ISSUE TITLE
Examples contain undefined behavior

### ISSUE THREAD

**Issue by nvssynthesis** [jatinchowdhury18/RTNeural#140]
In the "getModelFile" function, within the loop `while((--path.end())->string() != "RTNeural")
        path = path.parent_path();`, you are dereferencing an iterator with `(--path.end())->string()`. According to [cppreference](https://en.cppreference.com/w/cpp/filesystem/path/begin), "Dereferencing [the end] iterator is undefined behavior".
I believe this led to a bug at runtime using Clang. 

The implementation of getModelFile I ended up replacing it with (for now) looks like:

```
const std::string js_fn = "rt_models/my_model.json";
const std::string project_root = "RTNeural";

std::string getModelFile(fs::path path) {
    path = fs::absolute(path);

    std::vector<fs::path> components;

    while (!path.empty() && path.filename() != project_root) {
        components.push_back(path.filename());
        path = path.parent_path();
    }
    if (path.empty()) {
        throw std::runtime_error("Root directory not found");
    }

    fs::path resultPath = path / js_fn;

    return resultPath.string();
}
```

**Comment by jatinchowdhury18** [comment]
Good catch!

I do like your solution, but I'd prefer to keep the example code as focused as possible. With that in mind, I think it's best to keep the `getModelFile()` method minimal, even if it's not "bulletproof".

That said, potentially de-referencing `path.end()` isn't great, especially since implementations of the STL might flag it with a run-time assertion.

How's this as a minimal but better solution:
```cpp
// get path of RTNeural root directory
while(path.filename() != "RTNeural")
    path = path.parent_path();
```

**Comment by nvssynthesis** [comment]
Yeah, makes sense to keep it simple. That works!
